#!/bin/bash
find . -type f -name "*.gif" -print0 |
	awk -F'/' -v RS='\0' '{gsub(/\.[^.]+$/, "", $NF); print tolower($NF) "\t" $0}' |
LC_COLLATE=C sort -t$'\t' -f |
awk -F'\t' '{print $2}' |
tr '\0' '\n'
echo
